version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: web
    restart: always
    environment:
      TZ: 'Asia/Bangkok'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-data:/var/www/html
      - web-config:/etc/nginx
      - web-log:/var/log/nginx
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "nginx"
  php-80-01:
    image: bucchub/php-fpm:8.0
    container_name: php-80-01
    restart: always
    volumes:
      - web-data:/var/www/html
      - php-80-config:/usr/local/etc
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql/conf.d
    environment:
      TZ: 'Asia/Bangkok'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    #ports:
    #  - 3306:3306
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "mariadb"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      TZ: 'Asia/Bangkok'
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1024M
    ports:
      - 8081:80
networks:
  default:
    name: web
volumes:
  web-data:
  web-log:
  web-config:
  php-80-config:
  db-data:
  db-config:
